In [1]:
! pip install -U gym chainerrl

Requirement already up-to-date: gym in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (0.17.1)
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import gym
import numpy as np

In [4]:
# Agent 函示庫
import chainer
import chainerrl

In [5]:
# 產生環境
I_am_RL_Enviroment = gym.make('CartPole-v0')

# 視覺化 
# I_am_RL_Enviroment.render()
# 已將azure notebook的視覺化取消        


print("Observation Space : ")
print(I_am_RL_Enviroment.observation_space)
obs_size = I_am_RL_Enviroment.observation_space.shape[0]
print("Action Space : ")
print(I_am_RL_Enviroment.action_space)
n_actions = I_am_RL_Enviroment.action_space.n

Observation Space : 
Box(4,)
Action Space : 
Discrete(2)


In [6]:
# agent 參數設定

In [7]:
# Instance of Value function Q from "chainerrl.q_functions.FCStateQFunctionWithDiscreteAction"
I_Am_Q_Function = chainerrl.q_functions.FCStateQFunctionWithDiscreteAction(obs_size, n_actions,n_hidden_layers=4, n_hidden_channels=50)

In [8]:
# Instance of training optimizer from chainer.optimizers
optimizer = chainer.optimizers.Adam(eps=1e-2)
# set the oprimizer 
optimizer.setup(I_Am_Q_Function)

In [9]:
# Set the discount factor that discounts future rewards.
gamma = 0.9

# Use epsilon-greedy for exploration
explorer = chainerrl.explorers.ConstantEpsilonGreedy(
    epsilon=0.3, random_action_func=I_am_RL_Enviroment.action_space.sample)

# DQN uses Experience Replay.
# Specify a replay buffer and its capacity.
replay_buffer = chainerrl.replay_buffer.ReplayBuffer(capacity=10 ** 6)

# Since observations from CartPole-v0 is numpy.float64 while
# Chainer only accepts numpy.float32 by default, specify
# a converter as a feature extractor function phi.
phi = lambda x: x.astype(np.float32, copy=False)

# Now create an agent that will interact with the environment.
I_am_DQN_Agent = chainerrl.agents.DoubleDQN(
    I_Am_Q_Function, optimizer, replay_buffer, gamma, explorer,
    replay_start_size=500, update_interval=1,
    target_update_interval=100, phi=phi)

In [11]:
for i_episode in range(100): #how many episodes you want to run
    
    Observation_State = I_am_RL_Enviroment.reset() #reset() returns initial observation
    Step_Reward = 0
    Empirical_Reward = 0
    done = False
    
    for Step_T in range(100):
        
        # 視覺化 
        # I_am_RL_Enviroment.render()
        # 已將azure notebook的視覺化取消        

        
        print("I am step : {}".format(Step_T))
        print("============== Current Senario ==============")        
        print("Observation Space : ")
        print(I_am_RL_Enviroment.observation_space)
        print("Action Space : ")
        print(I_am_RL_Enviroment.action_space)

        
        print("============== Current Interaction  ==============")
        print("Current Observation : ")
        print(Observation_State)
        print("Current Action Select : ")
        
        
        # 將隨機行為換成 AI agent 行為 
        # Action_Select = I_am_RL_Enviroment.action_space.sample()
        
        # AI agent 依輸入的狀態與前項回饋產生行為以及訓練         
        Action_Select = I_am_DQN_Agent.act_and_train(Observation_State , Step_Reward)
        print(Action_Select)
        print("============== Current Interaction  ==============")

        
        print("============== Enviroment Interaction Result ==============")
        Observation_State, Step_Reward, Done, Infomation = I_am_RL_Enviroment.step(Action_Select)
        print("New Observation State from Enviroment Interaction  : ")
        print(Observation_State)
        print("Reward from Enviroment Interaction  : ")
        Step_Reward = Step_Reward
        print(Step_Reward)
        Empirical_Reward = Empirical_Reward + Step_Reward
        print("Infomation from Enviroment Interaction  : ")        
        print(Infomation)
        print("============== Enviroment Interaction Result ==============")
        
        if Done :
            print(" End of Step "*10)
            break
    
    print('episode:', i_episode, 'R:', Empirical_Reward, 'statistics:', I_am_DQN_Agent.get_statistics())
    I_am_DQN_Agent.stop_episode_and_train(Observation_State, Step_Reward, done)

I am step : 0
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.00665969  0.02527673  0.04730677 -0.01603782]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.00716523 -0.17049061  0.04698601  0.29118768]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.00716523 -0.17049061  0.04698601  0.29118768]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ====

============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.16078973 -1.60475888  0.19838326  2.50369464]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 8
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.16078973 -1.60475888  0.19838326  2.50369464]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.19288491 -1.80088916  0.24845715  2.85006272]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
 End

============== Enviroment Interaction Result ==============
I am step : 9
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.11936734 -0.93257802  0.08343096  1.48778169]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.1380189  -1.12861138  0.11318659  1.80530917]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 10
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.1380189  -1.12861138  0.11318659  1.80530917]
Current Action Select : 
0
============== Current Interaction  ===

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08705326 -0.97643245  0.04712512  1.46086649]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.08705326 -0.97643245  0.04712512  1.46086649]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.10658191 -1.17209939  0.07634245  1.76789073]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.04560305 -0.56993977  0.09188666  0.90450976]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05700184 -0.76617797  0.10997686  1.22460196]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 10
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.05700184 -0.76617797  0.10997686  1.22460196]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
Ne

Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.04463004  0.0289826   0.01212719 -0.03223329]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.04520969 -0.16631114  0.01148253  0.26425108]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.04520969 -0.16631114  0.01148253  0.26425108]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.04188347 -0.36159509  0.01676755  0.

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03006013 -1.19399485  0.0477418   1.74784552]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.03006013 -1.19399485  0.0477418   1.74784552]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05394003 -1.38962561  0.08269871  2.05498806]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.01069921 -0.36522458  0.0385369   0.62335914]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.01069921 -0.36522458  0.0385369   0.62335914]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.00339472 -0.56086281  0.05100408  0.92792565]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.00595208 -0.99449947  0.12203742  1.6225181 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.00595208 -0.99449947  0.12203742  1.6225181 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02584207 -1.19082874  0.15448779  1.95061177]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 8
============== Current Senario ==========

============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09145815 -0.99391823  0.10848868  1.60001298]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 11
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.09145815 -0.99391823  0.10848868  1.60001298]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.11133651 -1.19014512  0.14048894  1.92445601]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 12
============== Current Senario ========

============== Current Interaction  ==============
Current Observation : 
[-0.01839095 -0.37676584  0.04125584  0.66343777]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02592627 -0.57243672  0.05452459  0.96882013]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.02592627 -0.57243672  0.05452459  0.96882013]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.037375   -0.37808752  0.07390099  0.69375184]
Re

Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.04544247 -0.96950522  0.13556763  1.66693097]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.06483257 -1.16591878  0.16890625  1.998583  ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 10
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06483257 -1.16591878  0.16890625  1.998583  ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08815095 -1

I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06015713 -0.58768175 -0.02013184  0.86024172]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.07191076 -0.78252381 -0.00292701  1.14652724]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.07191076 -0.78252381 -0.00292701  1.14652724]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ====

Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.07110666 -0.7458606   0.11094683  1.2732919 ]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08602387 -0.55231524  0.13641267  1.01731031]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 9
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.08602387 -0.55231524  0.13641267  1.01731031]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09707017 -0.74896596

[-3.43593632e-02 -3.48081834e-01 -2.34384068e-06  5.67316550e-01]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-3.43593632e-02 -3.48081834e-01 -2.34384068e-06  5.67316550e-01]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.041321   -0.54320375  0.01134399  0.85999874]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Curre

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.17543058 -1.59895699  0.24689127  2.57148203]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
 End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step 
episode: 24 R: 10.0 statistics: [('average_q', 0.026123437924139143), ('average_loss', 0), ('n_updates', 0)]
I am step : 0
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.03891753 -0.02091871 -0.00296818  0.00128175]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.04418839 -0.20183554 -0.03856261  0.29298729]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.04418839 -0.20183554 -0.03856261  0.29298729]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0482251  -0.39638707 -0.03270287  0.57326302]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06239455 -1.00958574  0.01713842  1.37695345]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08258626 -0.81468202  0.04467749  1.08967925]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.08258626 -0.81468202  0.04467749  1.08967925]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0988799  -1.

{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.03432455  0.17131796  0.04021812 -0.31071992]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.0377509  -0.02435322  0.03400372 -0.00562955]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.0377509  -0.02435322  0.03400372 -0.00562955]
Current Action Select : 
0
============== Current Interaction  =

New Observation State from Enviroment Interaction  : 
[-0.06987666 -0.38329973  0.06695975  0.62415597]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 4
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06987666 -0.38329973  0.06695975  0.62415597]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.07754265 -0.18917337  0.07944287  0.35329044]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2

episode: 31 R: 9.0 statistics: [('average_q', 0.0324435335180054), ('average_loss', 0), ('n_updates', 0)]
I am step : 0
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.03094335 -0.04524116 -0.04313238  0.02937272]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.03003853 -0.23971887 -0.04254492  0.308141  ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.03003853 -0.23971887 -0.04254492  0.308141  ]
Current Action Select

============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08381487 -1.41051158  0.15734069  2.15297113]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.08381487 -1.41051158  0.15734069  2.15297113]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.1120251  -1.60679175  0.20040011  2.48982209]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am

============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.02816633 -0.22644681 -0.01740489  0.269296  ]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.02363739 -0.03108086 -0.01201897 -0.02882532]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.02363739 -0.03108086 -0.01201897 -0.02882532]
Current Action Select : 
0
============== Current Interaction  ====

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.15782079 -1.58692939  0.16819761  2.46722927]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 10
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.15782079 -1.58692939  0.16819761  2.46722927]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.18955938 -1.39357671  0.21754219  2.23051037]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03354842 -0.17550704 -0.00942786  0.27662237]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.03354842 -0.17550704 -0.00942786  0.27662237]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03705856 -0.37049322 -0.00389541  0.5663169 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.07771341 -0.93058189  0.08527821  1.51748007]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.07771341 -0.93058189  0.08527821  1.51748007]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09632505 -1.12662551  0.11562781  1.8355183 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

[-0.04425236 -1.1425437   0.21357035  2.03333803]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
 End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step 
episode: 42 R: 10.0 statistics: [('average_q', 0.040970697823604636), ('average_loss', 0), ('n_updates', 0)]
I am step : 0
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.03556241 -0.02181978  0.00243961 -0.01899874]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03599881 -0.21697664  0.00205963  0.27445291]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interact

{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.00153323 -0.38540233 -0.02066703  0.55250971]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.00924127 -0.58022804 -0.00961683  0.83861019]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.00924127 -0.58022804 -0.00961683  0.83861019]
Current Action Select : 
1
============== Current Interaction  =

Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06228975 -0.60248049  0.01030613  0.84732914]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.07433936 -0.7977415   0.02725271  1.14323505]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 4
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.07433936 -0.7977415   0.02725271  1.14323505]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09029419 -0.99320873

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.11917189 -1.38244923  0.15100628  2.15183391]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.11917189 -1.38244923  0.15100628  2.15183391]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.14682087 -1.57869953  0.19404296  2.48708673]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01652951 -0.41754729  0.00813334  0.57301914]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 4
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.01652951 -0.41754729  0.00813334  0.57301914]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02488045 -0.61278233  0.01959372  0.86825319]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01361749 -0.21058886 -0.0437321   0.24267125]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.01361749 -0.21058886 -0.0437321   0.24267125]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01782927 -0.40505975 -0.03887868  0.52124554]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.00380361 -0.18406795  0.03196942  0.2902144 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.00380361 -0.18406795  0.03196942  0.2902144 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 1.22254226e-04 -3.79630835e-01  3.77737037e-02  5.92806233e-01]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result =

1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[0.03519321 0.02114695 0.04429977 0.04420624]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 4
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[0.03519321 0.02114695 0.04429977 0.04420624]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.03561615 -0.17458133  0.0451839   0.35053049]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03689183 -0.76567964  0.04976921  1.125704  ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.03689183 -0.76567964  0.04976921  1.125704  ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05220542 -0.96141723  0.07228329  1.43357293]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09656386 -1.37326798  0.11710544  2.1017553 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 9
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.09656386 -1.37326798  0.11710544  2.1017553 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.12402922 -1.56935469  0.15914054  2.42822123]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

Current Observation : 
[-0.09486606 -1.16205835  0.1172123   1.7866158 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.11810723 -1.3582854   0.15294462  2.11331833]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 11
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.11810723 -1.3582854   0.15294462  2.11331833]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.14527293 -1.55456959  0.19521098  2.44909832]
Reward from Enviroment Interaction  : 
1.0
Infomatio

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02826011 -0.16640009  0.00582602  0.25358456]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.02826011 -0.16640009  0.00582602  0.25358456]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03158811 -0.36160474  0.01089771  0.5480994 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03154514 -1.20297873  0.04201556  1.67655226]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.03154514 -1.20297873  0.04201556  1.67655226]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05560472 -1.3985621   0.07554661  1.98201736]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.01749619 -0.36565865  0.03172658  0.55442578]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.01749619 -0.36565865  0.03172658  0.55442578]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.01018302 -0.56121139  0.0428151   0.85693333]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0215502  -0.56744922  0.08772051  0.97476175]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.0215502  -0.56744922  0.08772051  0.97476175]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03289918 -0.76363138  0.10721575  1.29366029]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0417243  -1.00277399  0.0744725   1.43940947]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 11
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.0417243  -1.00277399  0.0744725   1.43940947]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.06177978 -1.19873027  0.10326069  1.75440385]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I

1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.13280818 -0.76680372  0.15353827  1.26535675]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 12
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.13280818 -0.76680372  0.15353827  1.26535675]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.14814425 -0.96351764  0.17884541  1.60191955]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.06981939 -1.20747492  0.06452422  1.75978996]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06981939 -1.20747492  0.06452422  1.75978996]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09396889 -1.01314008  0.09972002  1.48785127]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.17478653 -1.73226069  0.20271858  2.76108402]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 11
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.17478653 -1.73226069  0.20271858  2.76108402]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.20943174 -1.92813253  0.25794026  3.10806733]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.04295142 -0.15281746 -0.03142308  0.22660887]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.04295142 -0.15281746 -0.03142308  0.22660887]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.04600777  0.04273915 -0.0268909  -0.0758181 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02624938 -0.54931802  0.0224798   0.9300868 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.02624938 -0.54931802  0.0224798   0.9300868 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03723574 -0.74473606  0.04108154  1.22974831]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01316398 -0.93692564  0.04209986  1.45399068]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.01316398 -0.93692564  0.04209986  1.45399068]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0319025  -1.13253849  0.07117967  1.75952367]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0761382  -0.57906059  0.17447492  1.04595889]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 9
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.0761382  -0.57906059  0.17447492  1.04595889]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08771942 -0.38662941  0.1953941   0.81273017]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01475288 -0.42920464 -0.00931451  0.59432049]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.01475288 -0.42920464 -0.00931451  0.59432049]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02333698 -0.62419499  0.0025719   0.8840549 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.07289122 -1.13973865  0.15733468  1.84189936]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 10
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.07289122 -1.13973865  0.15733468  1.84189936]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.095686   -1.33620842  0.19417267  2.17902973]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.00289435 -0.21961524  0.01608268  0.30561971]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.00289435 -0.21961524  0.01608268  0.30561971]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.00728665 -0.41496264  0.02219507  0.60333102]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.02879457 -0.18099902  0.0400872   0.32702017]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.02879457 -0.18099902  0.0400872   0.32702017]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.02517459 -0.37666809  0.04662761  0.63207046]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.09239939 -1.38154018  0.15898524  2.12307345]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 9
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.09239939 -1.38154018  0.15898524  2.12307345]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.1200302  -1.18831824  0.20144671  1.88344079]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05077797 -0.41634611  0.00315349  0.54966321]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 4
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.05077797 -0.41634611  0.00315349  0.54966321]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05910489 -0.61151221  0.01414675  0.84333803]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.02023332 -0.56353096 -0.02226179  0.83325659]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.02023332 -0.56353096 -0.02226179  0.83325659]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03150394 -0.75834177 -0.00559666  1.11885596]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

New Observation State from Enviroment Interaction  : 
[-0.00605394 -0.02173902  0.06581416  0.12146644]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.00605394 -0.02173902  0.06581416  0.12146644]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.00648872 -0.21773915  0.06824348  0.43416551]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05589711 -1.22411101  0.15033503  1.8950437 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 8
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.05589711 -1.22411101  0.15033503  1.8950437 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.08037933 -1.42050957  0.18823591  2.23035096]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.05533354 -0.77563834  0.03362909  1.19870169]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 4
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.05533354 -0.77563834  0.03362909  1.19870169]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0708463  -0.97117891  0.05760312  1.50173179]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.00240678 -0.16527608  0.02229861  0.34297335]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.00240678 -0.16527608  0.02229861  0.34297335]
Current Action Select : 
1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.00089874  0.02952165  0.02915808  0.05740464]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.01720063 -0.42555056 -0.04036662  0.56953157]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 2
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.01720063 -0.42555056 -0.04036662  0.56953157]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.00868962 -0.62008381 -0.02897599  0.84922918]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06100439 -0.34294244 -0.00561425  0.59749817]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.06786324 -0.53798538  0.00633571  0.88840739]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06786324 -0.53798538  0.00633571  0.88840739]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.07862295 -0.73319274  0.02410386  1.

1
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.06028294 -0.59656277  0.1034363   1.00855989]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 7
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.06028294 -0.59656277  0.1034363   1.00855989]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.0722142  -0.79290197  0.1236075   1.33185068]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01859982 -0.6308345  -0.02960255  0.86980282]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 3
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.01859982 -0.6308345  -0.02960255  0.86980282]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03121651 -0.82554152 -0.0122065   1.15303351]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.01509218 -1.16817912  0.06048686  1.7811449 ]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 6
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.01509218 -1.16817912  0.06048686  1.7811449 ]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.03845576 -1.36392699  0.09610975  2.09200203]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I 

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.11376733 -1.55618896  0.24634608  2.64821254]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
 End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step  End of Step 
episode: 94 R: 10.0 statistics: [('average_q', 1.3896478811656987), ('average_loss', 0.027330156810373096), ('n_updates', 552)]
I am step : 0
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.01669451 -0.03766852 -0.04891993  0.00138719]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ===========

0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.00265761 -0.55301475 -0.01559415  0.83165461]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 5
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.00265761 -0.55301475 -0.01559415  0.83165461]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-8.40268570e-03 -7.47920147e-01  1.03894514e-03  1.11939267e+00]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result =

[-0.1063026  -1.55499686  0.15127892  2.42922509]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 8
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[-0.1063026  -1.55499686  0.15127892  2.42922509]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[-0.13740254 -1.75106198  0.19986342  2.76427047]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 9
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
C

episode: 98 R: 13.0 statistics: [('average_q', 1.5758834205359027), ('average_loss', 0.017737956203225838), ('n_updates', 598)]
I am step : 0
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.03593819  0.02641105 -0.02817055 -0.02368802]
Current Action Select : 
0
============== Current Interaction  ==============
============== Enviroment Interaction Result ==============
New Observation State from Enviroment Interaction  : 
[ 0.03646641 -0.16829582 -0.02864431  0.25997536]
Reward from Enviroment Interaction  : 
1.0
Infomation from Enviroment Interaction  : 
{}
============== Enviroment Interaction Result ==============
I am step : 1
============== Current Senario ==============
Observation Space : 
Box(4,)
Action Space : 
Discrete(2)
============== Current Interaction  ==============
Current Observation : 
[ 0.03646641 -0.16829582 -0.02864431  0.25997536]