In [5]:
#numpy
import numpy as np

#產生陣列
a=np.array([10,20,30,40]) # array([10, 20, 30, 40])
print(a)
print(type(a))

#快速產生
b=np.arange(4)              # array([0, 1, 2, 3])
print(b)

#陣列相互運算
c=a-b  # array([10, 19, 28, 37])
print(c)
print(type(c))
c=a+b   # array([10, 21, 32, 43])
print(c)
c=a*b   # array([  0,  20,  60, 120])
print(c)
#陣列比較運算
print(b<2)  
# array([ True,  True,  True, False], dtype=bool)


#產生多維陣列
a=np.array([[1,1],[0,1]])
print(a)
# array([[1, 1],
#       [0, 1]])

#使用 reshap
b=np.arange(4).reshape((2,2))
print(b)
# array([[0, 1],
#       [2, 3]])


A = np.arange(2,14).reshape((3,4)) 

# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])
print(A)
print(np.argmin(A))    # 0
print(np.argmax(A))    # 11

[10 20 30 40]
<class 'numpy.ndarray'>
[0 1 2 3]
[10 19 28 37]
<class 'numpy.ndarray'>
[10 21 32 43]
[  0  20  60 120]
[ True  True False False]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


In [6]:
#pandas
import pandas

dates = pandas.date_range('20130101', periods=6)
df = pandas.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])
print(df)

#使用名稱列出欄位資料
print(df['A'])
print(df.A)

#使用位置列出列資料
print(df[0:3])
print(df['20130102':'20130104'])

#適用loc鎖定資料名稱
print(df.loc['20130102'])
print(df.loc[:,['A','B']]) 
print(df.loc['20130102',['A','B']])

#適用iloc鎖定資料位置
print(df.iloc[3,1])
print(df.iloc[3:5,1:3])
print(df.iloc[[1,3,5],1:3])


df.to_csv("IO_Practice_Folder/save_csv.csv")
pandas.read_csv("IO_Practice_Folder/save_csv.csv")

             A   B   C   D
2013-01-01   0   1   2   3
2013-01-02   4   5   6   7
2013-01-03   8   9  10  11
2013-01-04  12  13  14  15
2013-01-05  16  17  18  19
2013-01-06  20  21  22  23
2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int64
2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int64
            A  B   C   D
2013-01-01  0  1   2   3
2013-01-02  4  5   6   7
2013-01-03  8  9  10  11
             A   B   C   D
2013-01-02   4   5   6   7
2013-01-03   8   9  10  11
2013-01-04  12  13  14  15
A    4
B    5
C    6
D    7
Name: 2013-01-02 00:00:00, dtype: int64
             A   B
2013-01-01   0   1
2013-01-02   4   5
2013-01-03   8   9
2013-01-04  12  13
2013-01-05  16  17
2013-01-06  20  21
A    4
B    5
Name: 2013-01-02 00:00:00, dtype: int64
13
             B   C
2013-01-04  13  14
2013-01-05  17  18
             B   C
201

Unnamed: 0   A   B   C   D
0  2013-01-01   0   1   2   3
1  2013-01-02   4   5   6   7
2  2013-01-03   8   9  10  11
3  2013-01-04  12  13  14  15
4  2013-01-05  16  17  18  19
5  2013-01-06  20  21  22  23